name: 'Publish Docker'
author: 'Brett Mayson & Prince Singh'
branding:
  icon: 'anchor'
  color: 'blue'
description: 'Uses the git branch as the docker tag and pushes the container'
inputs:
  name:
    description: 'The name of the image you would like to push'
    required: true
  username:
    description: 'The login username for the registry'
    required: true
  password:
    description: 'The login password for the registry'
    required: true
  registry:
    description: 'Use registry for pushing to a custom registry'
    required: false
  workdir:
    description: 'Use workdir when you would like to change the directory for building'
    required: false
    default: .
  buildargs:
    description: 'Use buildargs when you want to pass a list of environment variables as build-args'
    required: false
  tags:
    description: 'Use tags when you want to bring your own tags (separated by comma)'
    required: false
outputs:
  tag:
    description: 'Is the tag, which was pushed'
runs:
  using: 'node12'
  main: 'dist/index.js'
